# Generated by Django 6.0.4 on 2026-06-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
